FROM golang:1.20-alpine as builder

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /app/main .

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/main /app/main

RUN chmod +x /app/main

EXPOSE 8080

CMD ["/app/main"]
